### PR TITLE
CSVImport Resource identifier

### PR DESCRIPTION
**Pull request by allanaaa**
Closes https://github.com/omeka-s-modules/CSVImport/issues/216

### CODE REVIEW

**Comment by allanaaa** [comment]
@zerocrates I think this covers everything (with some misc image-fixing thrown in too).

**Comment by zerocrates** [comment]
The image fixes are mostly just stuff that's gotten out of date, yeah?

**Comment by allanaaa** [comment]
That and some things that needed better cropping.

**Comment by allanaaa** [comment]
Updated to remove error message that is solved by https://github.com/omeka-s-modules/CSVImport/tree/append-errors.

**Pull request merged**
