### PR TITLE
Extract Text

### PR DESCRIPTION
**Pull request by allanaaa**
Closes https://github.com/omeka-s-modules/ExtractText/issues/8.

### CODE REVIEW

**Comment by allanaaa** [comment]
Note to self: delete old image.

**Comment by katknow** [comment]
@allanaaa I was able to follow the documentation and make it work, so I'd say this is good!

**Comment by allanaaa** [comment]
Great, thanks! 

@jimsafley Ready to merge when you are, unless you see anything worth changing.

**Comment by jimsafley** [comment]
Fantastic docs! Thank you.

**Pull request merged**
